INSERT INTO subreddits (name, description) VALUES
    ('funny', 'A place for humor and jokes'),
    ('pics', 'A place for pictures'),
    ('gaming', 'A place for gaming'),
    ('movies', 'A place for movies'),
    ('news', 'A place for news'),
    ('science', 'A place for science'),
    ('technology', 'A place for technology'),
    ('worldnews', 'A place for world news'),
    ('askreddit', 'A place for ask reddit'),
    ('gifs', 'A place for gifs'),
    ('todayilearned', 'A place for today I learned'),
    ('videos', 'A place for videos'),
    ('aww', 'A place for aww'),
    ('music', 'A place for music'),
    ('blog', 'A place for blog'),
    ('books', 'A place for books'),
    ('food', 'A place for food'),
    ('gadgets', 'A place for gadgets'),
    ('lifehacks', 'A place for life hacks'),
    ('mildlyinteresting', 'A place for mildly interesting'),
    ('space', 'A place for space'),
    ('sports', 'A place for sports'),
    ('television', 'A place for television'),
    ('travel', 'A place for travel'),
    ('writingprompts', 'A place for writing prompts');